# Generated by Django 5.1.6 on 2025-03-02 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
    ]
