# Generated by Django 5.1.6 on 2025-03-03 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_anime_watch_status'),
    ]

    operations = [
    ]
