# Generated by Django 5.1.6 on 2025-03-03 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20250303_1633'),
    ]

    operations = [
    ]
