# Generated by Django 5.1.6 on 2025-03-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_anime_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(related_name='animes', to='core.genre'),
        ),
    ]
